# Generated by Django 5.1.6 on 2025-04-01 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='cveRegistro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.registro'),
        ),
    ]
