# Generated by Django 5.1.6 on 2025-04-03 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dispositivo_cveregistro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='cveRegistro',
        ),
    ]
