# Generated by Django 5.2 on 2025-04-09 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_dispositivo_cveregistro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('rol', models.CharField(max_length=25)),
                ('usuario', models.CharField(max_length=30, unique=True)),
                ('contrasenia', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Invernadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.CharField(max_length=70)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invernaderos', to='dashboard.cultivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invernaderos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Temperatura', 'Temperatura'), ('Humedad', 'Humedad'), ('Luz', 'Luz'), ('Sueldo', 'Sueldo')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_instalacion', models.DateTimeField(auto_now_add=True)),
                ('invernadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='dashboard.invernadero')),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Sensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='dashboard.sensor')),
            ],
        ),
    ]
